import { Dimensions, Platform, StatusBar, StyleSheet } from "react-native";
import { brutalistColors, colors } from "./colors";

const { width: screenWidth } = Dimensions.get("window");
const MAX_WAVEFORM_WIDTH = screenWidth - 60;

export const globalStyles = StyleSheet.create({
  container: {
    paddingTop: 20,
    flex: 1,
    backgroundColor: colors.offwhite,
  },
});

export const homeStyles = StyleSheet.create({
  container: {
    flex: 1,
    padding: 20,
    justifyContent: "center",
  },
  title: {
    fontSize: 24,
    fontWeight: "bold",
    textAlign: "center",
    marginBottom: 8,
    color: colors.gray.dark,
  },
  subtitle: {
    fontSize: 16,
    textAlign: "center",
    marginBottom: 40,
    color: colors.gray.medium,
  },
});

export const photoGridStyles = StyleSheet.create({
  container: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 30,
    paddingHorizontal: 10,
  },
  photoContainer: {
    alignItems: "center",
    flex: 1,
    marginHorizontal: 5,
  },
  photoNumber: {
    fontSize: 18,
    fontWeight: "bold",
    color: colors.primary[500],
    marginBottom: 10,
  },
  photoWrapper: {
    position: "relative",
  },
  photoPreview: {
    width: 100,
    height: 120,
    borderRadius: 8,
    backgroundColor: "#e0e0e0",
  },
  emptySlot: {
    width: 100,
    height: 120,
    borderRadius: 8,
    backgroundColor: "#e0e0e0",
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 2,
    borderColor: colors.gray.light,
    borderStyle: "dashed",
  },
  retakeButton: {
    position: "absolute",
    bottom: -25,
    alignSelf: "center",
    backgroundColor: colors.background.secondary,
    paddingHorizontal: 12,
    paddingVertical: 4,
    borderRadius: 12,
  },
  retakeButtonText: {
    color: colors.white,
    fontSize: 12,
    fontWeight: "600",
  },
});

export const audioStyles = StyleSheet.create({
  preview: {
    width: "100%",
    borderWidth: 4,
    borderColor: "#000",
    backgroundColor: "#fff",
    padding: 24,
    alignItems: "center",
  },
  previewText: {
    marginTop: 16,
    color: "#000",
    fontSize: 16,
    lineHeight: 1.4,
    fontWeight: "900",
    textTransform: "uppercase",
  },
  controls: {
    flexDirection: "row",
    marginTop: 20,
    gap: 16,
    width: "100%",
  },
  playButton: {
    flex: 1,
    borderWidth: 3,
    borderColor: "#000",
    backgroundColor: "#000",
    color: "#fff",
    padding: 12,
    justifyContent: "center",
    alignItems: "center",
  },
  deleteButton: {
    flex: 1,
    borderWidth: 3,
    borderColor: "#000",
    backgroundColor: "#fff",
    color: "#000",
    padding: 12,
    justifyContent: "center",
    alignItems: "center",
  },
});

export const cameraStyles = StyleSheet.create({
  container: {
    flex: 1,
  },
  camera: {
    flex: 1,
  },
  backButton: {
    position: "absolute",
    top: 60,
    left: 20,
    backgroundColor: colors.transparent.black50,
    padding: 12,
    borderRadius: 20,
    zIndex: 1,
  },
  counterOverlay: {
    position: "absolute",
    top: 60,
    alignSelf: "center",
    backgroundColor: colors.transparent.black70,
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 20,
  },
  counterText: {
    color: colors.white,
    fontSize: 16,
    fontWeight: "600",
  },
  shutterContainer: {
    position: "absolute",
    bottom: 44,
    left: 0,
    width: "100%",
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "center",
    paddingHorizontal: 30,
  },
  controlSpacer: {
    display: "none",
  },
  shutterBtn: {
    alignItems: "center",
    justifyContent: "center",
  },
  shutterBtnOuter: {
    backgroundColor: "transparent",
    borderWidth: 5,
    borderColor: colors.white,
    width: 85,
    height: 85,
    borderRadius: 45,
    alignItems: "center",
    justifyContent: "center",
  },
  shutterBtnInner: {
    backgroundColor: colors.white,
    width: 70,
    height: 70,
    borderRadius: 35,
  },
  controlBtn: {
    width: 32,
    height: 32,
    alignItems: "center",
    justifyContent: "center",
  },
});

export const audioRecorderStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#fff",
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    paddingTop: 60,
    paddingHorizontal: 20,
    paddingBottom: 16,
    borderBottomWidth: 4,
    borderColor: "#000",
  },
  backButton: {
    padding: 8,
  },
  title: {
    color: "#000",
    fontSize: 24,
    fontWeight: "900",
    marginLeft: 16,
    textTransform: "uppercase",
  },
  content: {
    flex: 1,
    justifyContent: "flex-start",
    padding: 20,
  },
  datePrompt: {
    alignItems: "center",
    paddingVertical: 16,
    paddingHorizontal: 20,
    backgroundColor: "#fff",
    borderWidth: 2,
    borderColor: "#000",
    borderStyle: "dashed",
    marginBottom: 20,
  },
  dateText: {
    fontSize: 16,
    fontWeight: "600",
    color: "#000",
    textAlign: "center",
  },
  waveformContainer: {
    height: 120,
    borderWidth: 4,
    borderColor: "#000",
    backgroundColor: "#fff",
    flexDirection: "row",
    alignItems: "center",
    overflow: "hidden",
    marginVertical: 20,
  },
  waveform: {
    flexDirection: "row",
    gap: 3,
    alignItems: "center",
  },
  durationContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 10,
    marginBottom: 10,
  },
  durationText: {
    color: "#000",
    fontSize: 16,
    fontWeight: "600",
  },
  statusIndicator: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 20,
    paddingVertical: 10,
    borderTopWidth: 2,
    borderBottomWidth: 2,
    borderColor: "#000",
  },
  recordingDot: {
    width: 12,
    height: 12,
    backgroundColor: "#FF3B30",
    marginRight: 12,
  },
  statusText: {
    color: "#000",
    fontSize: 18,
    fontWeight: "900",
    textTransform: "uppercase",
  },
  controlsContainer: {
    padding: 20,
    borderTopWidth: 4,
    borderColor: "#000",
  },
  controlButtonBase: {
    justifyContent: "center",
    alignItems: "center",
    padding: 16,
    borderWidth: 4,
    borderColor: "#000",
  },
  recordButton: {
    backgroundColor: "#000",
  },
  stopButton: {
    backgroundColor: "#FF3B30",
  },
  playbackControls: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 10,
  },
  retakeButton: {
    flex: 1,
    backgroundColor: "#fff",
  },
  playPauseButton: {
    flex: 1,
    backgroundColor: "#fff",
  },
  completeButton: {
    flex: 1,
    backgroundColor: "#000",
  },
});

// export const actionButtonStyles = StyleSheet.create({
//   container: {
//     paddingHorizontal: 20,
//   },
//   row: {
//     flexDirection: "row",
//     justifyContent: "space-between",
//     gap: 15,
//   },
//   primaryButton: {
//     backgroundColor: colors.background.primary,
//     paddingVertical: 15,
//     paddingHorizontal: 30,
//     borderRadius: 25,
//     alignItems: "center",
//   },
//   primaryButtonText: {
//     color: colors.white,
//     fontSize: 18,
//     fontWeight: "600",
//   },
//   secondaryButton: {
//     backgroundColor: colors.background.secondary,
//     paddingVertical: 15,
//     paddingHorizontal: 30,
//     borderRadius: 25,
//     flex: 1,
//     alignItems: "center",
//   },
//   secondaryButtonText: {
//     color: colors.white,
//     fontSize: 18,
//     fontWeight: "600",
//   },
// });

export const loadingStyles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: colors.black,
  },
  text: {
    color: colors.white,
    fontSize: 18,
    marginTop: 20,
    fontWeight: "600",
  },
  subtext: {
    color: "#888",
    fontSize: 14,
    marginTop: 8,
  },
});

export const mapCardStyles = StyleSheet.create({
  container: {
    margin: 20,
    marginBottom: 10,
    borderWidth: 2,
    borderColor: "#000",
    backgroundColor: "#fff",
    shadowColor: "#000",
    shadowOffset: { width: 6, height: 6 },
    shadowOpacity: 0,
    shadowRadius: 0,
    elevation: 8,
    overflow: "hidden",
  },

  mapContainer: {
    height: 300,
    position: "relative",
    borderBottomWidth: 2,
    borderColor: "#000",
    overflow: "hidden",
  },

  expandButton: {
    position: "absolute",
    bottom: 10,
    left: 10,
    backgroundColor: "#000",
    padding: 8,
    width: 40,
    height: 40,
    borderWidth: 2,
    borderColor: "#000",
    justifyContent: "center",
    alignItems: "center",
    zIndex: 10,
  },

  recenterButton: {
    position: "absolute",
    bottom: 12,
    right: 12,
    backgroundColor: "#fff",
    padding: 10,
    width: 44,
    height: 44,
    borderWidth: 3,
    borderColor: "#000",
    justifyContent: "center",
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: { width: 4, height: 4 },
    shadowOpacity: 1,
    shadowRadius: 0,
    elevation: 6,
  },
});

export const expandedMapStyles = StyleSheet.create({
  recenterButton: {
    position: "absolute",
    bottom: 40,
    right: 20,
    backgroundColor: "rgba(0, 122, 255, 0.9)",
    padding: 12,
    borderRadius: 30,
    justifyContent: "center",
    alignItems: "center",
    zIndex: 10,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 6,
  },
  container: {
    flex: 1,
    position: "relative",
  },
  closeButton: {
    position: "absolute",
    top: 60,
    right: 20,
    backgroundColor: "rgba(0, 0, 0, 0.7)",
    padding: 12,
    borderRadius: 20,
    zIndex: 1000,
    width: 48,
    height: 48,
    justifyContent: "center",
    alignItems: "center",
  },
  dropdownContainer: {
    position: "absolute",
    bottom: 20,
    left: 0,
    right: 0,
    zIndex: 1001,
    paddingHorizontal: 16,
  },
  mapContainer: {
    flex: 1,
  },
});

export const mapStyles = StyleSheet.create({
  container: {
    flex: 1,
  },
  loadingContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#f5f5f5",
  },
  loadingText: {
    marginTop: 8,
    fontSize: 12,
    color: "#666",
  },
});

// export const locationStatusStyles = StyleSheet.create({
//   container: {
//     position: "absolute",
//     top: 10,
//     left: 10,
//     right: 10,
//     paddingHorizontal: 12,
//     paddingVertical: 8,
//     borderRadius: 6,
//     flexDirection: "row",
//     alignItems: "center",
//     shadowColor: "#000",
//     shadowOffset: { width: 0, height: 1 },
//     shadowOpacity: 0.22,
//     shadowRadius: 2.22,
//     elevation: 3,
//   },
//   inside: {
//     backgroundColor: "#d4edda",
//     borderColor: "#c3e6cb",
//     borderWidth: 1,
//   },
//   outside: {
//     backgroundColor: "#f8d7da",
//     borderColor: "#f5c6cb",
//     borderWidth: 1,
//   },
//   icon: {
//     fontSize: 16,
//     marginRight: 8,
//     color: "#495057",
//   },
//   text: {
//     fontSize: 12,
//     fontWeight: "500",
//     color: "#495057",
//     flex: 1,
//   },
// });

export const attendanceContainerStyles = StyleSheet.create({
  container: {
    marginTop: 40,
  },
  contentContainer: {
    paddingBottom: 20,
  },

  fieldTripContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    padding: 20,
  },
  fieldTripGradient: {
    width: "100%",
    padding: 30,
    borderRadius: 20,
    alignItems: "center",
    justifyContent: "center",
    minHeight: 300,
  },
  fieldTripTitle: {
    fontSize: 28,
    fontWeight: "bold",
    color: colors.white,
    marginTop: 20,
    marginBottom: 12,
    textAlign: "center",
  },
  fieldTripText: {
    fontSize: 16,
    color: colors.white,
    textAlign: "center",
    marginBottom: 30,
    opacity: 0.9,
    lineHeight: 24,
  },
  fieldTripInfo: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "rgba(255, 255, 255, 0.2)",
    paddingHorizontal: 20,
    paddingVertical: 12,
    borderRadius: 25,
    gap: 10,
  },
  fieldTripDate: {
    fontSize: 16,
    fontWeight: "600",
    color: colors.white,
  },
});

// export const dropdownStyles = {
//   container: {
//     marginHorizontal: 16,
//     marginVertical: 12,
//     zIndex: 1000,
//   },
//   selector: {
//     flexDirection: "row" as const,
//     alignItems: "center" as const,
//     justifyContent: "space-between" as const,
//     backgroundColor: "#fff",
//     borderRadius: 8,
//     borderWidth: 1,
//     borderColor: "#ddd",
//     paddingHorizontal: 16,
//     paddingVertical: 12,
//     minHeight: 48,
//   },
//   selectorText: {
//     flex: 1,
//     fontSize: 16,
//     color: "#333",
//     marginRight: 8,
//   },
//   modalOverlay: {
//     flex: 1,
//     backgroundColor: "rgba(0, 0, 0, 0.5)",
//     justifyContent: "center" as const,
//     alignItems: "center" as const,
//     paddingHorizontal: 20,
//   },
//   dropdownMenu: {
//     backgroundColor: "#fff",
//     borderRadius: 8,
//     maxHeight: 300,
//     minWidth: 250,
//     maxWidth: 350,
//     elevation: 5,
//     shadowColor: "#000",
//     shadowOffset: { width: 0, height: 2 },
//     shadowOpacity: 0.25,
//     shadowRadius: 8,
//   },
//   option: {
//     flexDirection: "row" as const,
//     alignItems: "center" as const,
//     justifyContent: "space-between" as const,
//     paddingHorizontal: 16,
//     paddingVertical: 14,
//     borderBottomWidth: 1,
//     borderBottomColor: "#f0f0f0",
//   },
//   selectedOption: {
//     backgroundColor: "#f8f9ff",
//   },
//   optionText: {
//     flex: 1,
//     fontSize: 16,
//     color: "#333",
//   },
//   selectedOptionText: {
//     color: "#007AFF",
//     fontWeight: "500" as const,
//   },
// };

export const actionButtonStyles = StyleSheet.create({
  container: {
    gap: 16,
    paddingHorizontal: 16,
  },
  buttonGroup: {
    gap: 16,
    alignItems: "stretch",
  },
  primaryButton: {
    borderWidth: 4,
    borderColor: colors.black,
    backgroundColor: colors.black,
    shadowColor: colors.black,
    shadowOffset: { width: 6, height: 6 },
    shadowOpacity: 1,
    shadowRadius: 0,
    elevation: 6,
    alignSelf: "stretch",
  },
  brutalistButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 10,
    paddingVertical: 18,
    paddingHorizontal: 24,
  },
  brutalistButtonText: {
    color: colors.white,
    fontSize: 16,
    fontWeight: "900",
    textTransform: "uppercase",
  },
  successButton: {
    backgroundColor: colors.success,
  },
  disabledButton: {
    backgroundColor: colors.gray[500],
  },
  secondaryButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 10,
    backgroundColor: colors.white,
    paddingVertical: 16,
    paddingHorizontal: 24,
    borderWidth: 4,
    borderColor: colors.black,
    shadowColor: colors.black,
    shadowOffset: { width: 6, height: 6 },
    shadowOpacity: 1,
    shadowRadius: 0,
    elevation: 6,
    alignSelf: "stretch",
  },
  secondaryButtonText: {
    color: colors.black,
    fontSize: 16,
    fontWeight: "900",
    textTransform: "uppercase",
  },
  buttonDisabled: {
    opacity: 0.6,
  },
});

export const audioSectionStyles = StyleSheet.create({
  container: {
    // No specific container styles needed, the card will define its own space
  },
  brutalistCard: {
    borderWidth: 4,
    borderColor: "#000",
    backgroundColor: "#fff",
    padding: 24, // 1.5rem equivalent
    borderStyle: "dashed",
  },
  brutalistCardHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 16, // 1rem equivalent
    marginBottom: 16,
    borderBottomWidth: 2,
    borderColor: "#000",
    paddingBottom: 16,
  },
  brutalistCardIcon: {
    flexShrink: 0,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#000",
    padding: 8, // 0.5rem equivalent
    width: 48,
    height: 48,
  },
  brutalistCardAlert: {
    fontWeight: "900",
    color: "#000",
    fontSize: 24, // 1.5rem equivalent
    textTransform: "uppercase",
  },
  brutalistCardMessage: {
    marginTop: 16,
    paddingBottom: 16,
  },
  recordButtonText: {
    fontSize: 18,
    fontWeight: "700",
    textTransform: "uppercase",
    color: "#000",
    marginBottom: 4,
  },
  recordHintText: {
    fontSize: 14,
    color: "#000",
    lineHeight: 20,
    fontWeight: "600",
  },
});

export const holidayScreenStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.offwhite,
    marginTop: 64,
  },
  headerCard: {
    margin: 16,
    padding: 24,
    borderWidth: 3,
    borderColor: "#000",
    borderRadius: 0,
    alignItems: "center",
  },
  headerContent: {
    alignItems: "center",
    gap: 12,
  },
  iconContainer: {
    width: 80,
    height: 80,
    borderWidth: 2,
    borderColor: "#000",
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 12,
    backgroundColor: "#00000022",
  },
  emoji: {
    fontSize: 42,
  },
  headerTitle: {
    fontSize: 26,
    fontWeight: "900",
    color: "#fff",
    textAlign: "center",
  },
  headerSubtitle: {
    fontSize: 16,
    fontWeight: "500",
    color: "#fff",
    textAlign: "center",
  },
  contentCard: {
    backgroundColor: "#fff",
    marginHorizontal: 16,
    marginBottom: 16,
    padding: 20,
    borderWidth: 3,
    borderColor: "#000",
    borderRadius: 0,
  },
  messageContainer: {
    alignItems: "center",
    gap: 8,
  },
  messageTitle: {
    fontSize: 18,
    fontWeight: "800",
    color: "#000",
    textAlign: "center",
  },
  messageText: {
    fontSize: 14,
    color: "#000",
    textAlign: "center",
    lineHeight: 20,
  },
  divider: {
    height: 2,
    backgroundColor: "#000",
    marginVertical: 16,
  },
  dateContainer: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    marginBottom: 16,
  },
  dateText: {
    fontSize: 14,
    fontWeight: "600",
    color: "#000",
  },
  tipsContainer: {
    backgroundColor: "#f5f5f5",
    padding: 16,
    borderWidth: 2,
    borderColor: "#000",
    borderRadius: 0,
    gap: 10,
  },
  tipsTitle: {
    fontSize: 15,
    fontWeight: "800",
    color: "#000",
    marginBottom: 8,
  },
  tipItem: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 8,
  },
  tipText: {
    flex: 1,
    fontSize: 13,
    color: "#000",
    lineHeight: 18,
  },
  bottomCard: {
    marginHorizontal: 16,
    marginBottom: 24,
    padding: 20,
    borderWidth: 3,
    borderColor: "#000",
    borderRadius: 0,
    backgroundColor: "#fff",
    alignItems: "center",
  },
  quoteText: {
    fontSize: 15,
    fontWeight: "600",
    color: "#000",
    textAlign: "center",
    marginBottom: 8,
    lineHeight: 22,
  },
  quoteAuthor: {
    fontSize: 13,
    fontWeight: "700",
    color: "#000",
  },
});

export const homeViewStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.offwhite,
  },
  brutalistCard: {
    borderWidth: 4,
    borderColor: brutalistColors.black,
    backgroundColor: brutalistColors.white,
    padding: 20,
    margin: 16,
    shadowColor: brutalistColors.black,
    shadowOffset: { width: 10, height: 10 },
    shadowOpacity: 1,
    shadowRadius: 0,
    elevation: 10,
  },
  headerCard: {
    margin: 16,
    borderWidth: 4,
    borderColor: brutalistColors.black,
    backgroundColor: colors.lightGreen,
    padding: 20,
    shadowColor: brutalistColors.black,
    shadowOffset: { width: 10, height: 10 },
    shadowOpacity: 1,
    shadowRadius: 0,
    elevation: 10,
  },
  headerContent: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  headerTextContainer: {
    flex: 1,
  },
  greeting: {
    fontSize: 14,
    color: brutalistColors.black,
    marginBottom: 4,
    fontWeight: "bold",
  },
  headerTitle: {
    fontSize: 24,
    fontWeight: "900",
    color: brutalistColors.black,
    marginBottom: 4,
    textTransform: "uppercase",
  },
  headerSubtitle: {
    fontSize: 14,
    color: brutalistColors.black,
    textTransform: "uppercase",
    flexWrap: "wrap",
    maxWidth: "100%",
  },
  headerIcon: {
    marginLeft: 16,
  },
  statsRow: {
    flexDirection: "row",
    borderWidth: 2,
    borderColor: brutalistColors.black,
    padding: 16,
    marginTop: 20,
    backgroundColor: brutalistColors.white,
  },
  statItem: {
    flex: 1,
    alignItems: "center",
  },
  statValue: {
    fontSize: 20,
    fontWeight: "900",
    color: brutalistColors.black,
    marginBottom: 4,
  },
  statLabel: {
    fontSize: 12,
    color: brutalistColors.black,
    fontWeight: "bold",
    textTransform: "uppercase",
  },
  statDivider: {
    width: 2,
    backgroundColor: brutalistColors.black,
  },
  sectionCard: {
    borderWidth: 4,
    borderColor: brutalistColors.black,
    backgroundColor: brutalistColors.white,
    marginHorizontal: 16,
    marginBottom: 16,
    padding: 20,
    shadowColor: brutalistColors.black,
    shadowOffset: { width: 10, height: 10 },
    shadowOpacity: 1,
    shadowRadius: 0,
    elevation: 10,
  },
  sectionHeader: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 8,
    borderBottomWidth: 2,
    borderColor: brutalistColors.black,
    paddingBottom: 8,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: "900",
    color: brutalistColors.black,
    marginLeft: 8,
    textTransform: "uppercase",
  },
  sectionDescription: {
    fontSize: 14,
    color: brutalistColors.black,
    marginBottom: 16,
    fontWeight: "600",
  },
  actionSection: {
    paddingHorizontal: 16,
    paddingBottom: 24,
  },
  attendanceMarkedCard: {
    borderWidth: 4,
    borderColor: brutalistColors.black,
    backgroundColor: brutalistColors.white,
    marginHorizontal: 16,
    marginBottom: 16,
    padding: 20,
    shadowColor: brutalistColors.black,
    shadowOffset: { width: 10, height: 10 },
    shadowOpacity: 1,
    shadowRadius: 0,
    elevation: 10,
  },
  attendanceMarkedContent: {
    flexDirection: "row",
    alignItems: "center",
  },
  attendanceMarkedIcon: {
    marginRight: 16,
  },
  attendanceMarkedText: {
    flex: 1,
  },
  attendanceMarkedTitle: {
    fontSize: 20,
    fontWeight: "900",
    color: brutalistColors.black,
    marginBottom: 4,
    textTransform: "uppercase",
  },
  attendanceMarkedSubtitle: {
    fontSize: 14,
    color: brutalistColors.black,
    marginBottom: 8,
    fontWeight: "600",
  },
  attendanceMarkedTime: {
    fontSize: 12,
    color: brutalistColors.gray,
  },
  summaryRow: {
    gap: 12,
    marginTop: 12,
  },
  summaryItem: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  summaryText: {
    fontSize: 14,
    color: brutalistColors.black,
    fontWeight: "600",
  },
  sessionIndicator: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    borderWidth: 2,
    paddingHorizontal: 12,
    paddingVertical: 8,
    marginTop: 16,
  },
  sessionText: {
    fontSize: 14,
    fontWeight: "bold",
    textTransform: "uppercase",
  },
  checkoutButtonContainer: {
    marginVertical: 16,
    alignItems: "center",
  },
  checkoutButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 16,
    paddingHorizontal: 24,
    backgroundColor: "#fff",
    borderWidth: 2,
    borderColor: brutalistColors.error,
    borderRadius: 4,
    shadowOffset: { width: 4, height: 4 },
    shadowOpacity: 1,
    shadowRadius: 0,
    elevation: 3,
  },
  checkoutButtonText: {
    fontSize: 18,
    fontWeight: "bold",
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
  buttonDisabled: {
    borderColor: brutalistColors.gray,
    shadowColor: brutalistColors.gray,
  },
  checkedOutButton: {
    borderColor: brutalistColors.success,
  },
  autoCompletedButton: {
    borderColor: brutalistColors.warning,
    shadowColor: brutalistColors.warning,
  },
  statusCard: {
    backgroundColor: brutalistColors.white,
    borderWidth: 2,
    padding: 16,
    marginTop: 16,
  },
  statusHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    marginBottom: 12,
    flexWrap: "wrap",
  },
  statusTitle: {
    fontSize: 16,
    fontWeight: "900",
    textTransform: "uppercase",
    flex: 1,
    flexWrap: "wrap",
  },
  statusDetails: {
    marginTop: 12,
    padding: 12,
    backgroundColor: "#F5F5F5",
    borderWidth: 1,
    borderColor: "#000000",
    borderRadius: 8,
    gap: 8,
  },
  statusRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 12,
  },
  statusLabel: {
    fontSize: 14,
    color: brutalistColors.gray,
    fontWeight: "bold",
    textTransform: "uppercase",
    minWidth: 90,
  },
  statusValue: {
    fontSize: 14,
    fontWeight: "600",
    color: brutalistColors.black,
    flex: 1,
    flexWrap: "wrap",
  },
  locationTypeBadge: {
    backgroundColor: brutalistColors.white,
    paddingHorizontal: 8,
    paddingVertical: 4,
    marginTop: 8,
    alignSelf: "flex-start",
  },
  locationTypeText: {
    fontSize: 12,
    color: brutalistColors.black,
    fontWeight: "900",
    textTransform: "uppercase",
  },
  statusText: {
    fontSize: 16,
    fontWeight: "600",
    color: brutalistColors.black,
  },
  cannotMarkBanner: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    backgroundColor: brutalistColors.errorBg,
    paddingVertical: 10,
    paddingHorizontal: 12,
    marginTop: 16,
    borderWidth: 2,
    borderColor: brutalistColors.black,
  },
  cannotMarkBannerText: {
    color: brutalistColors.black,
    fontSize: 14,
    fontWeight: "900",
    textTransform: "uppercase",
  },
  locationStatusCard: {
    borderWidth: 2,
    borderColor: brutalistColors.black,
    backgroundColor: brutalistColors.white,
    padding: 16,
    marginTop: -2,
    gap: 12,
  },
  validationErrorCard: {
    borderWidth: 2,
    borderColor: brutalistColors.black,
    backgroundColor: brutalistColors.errorBg,
    padding: 16,
    marginTop: 12,
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  validationErrorText: {
    color: brutalistColors.black,
    fontSize: 14,
    fontWeight: "bold",
    flex: 1,
    lineHeight: 20,
  },
});

export const attendancePhotoGridStyles = StyleSheet.create({
  container: {
    alignItems: "center",
    justifyContent: "center",
    width: "100%",
  },
  singlePhotoContainer: {
    width: "100%",
    maxWidth: 250,
    position: "relative",
    alignSelf: "center",
  },
  photoWrapper: {
    position: "relative",
    overflow: "hidden",
    borderWidth: 4,
    borderColor: brutalistColors.black,
    backgroundColor: brutalistColors.white,
  },

  photoPreview: {
    width: "100%",
    aspectRatio: 0.75,
    backgroundColor: brutalistColors.lightGray,
  },

  retakeOverlay: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: brutalistColors.lightGray,
    paddingVertical: 12,
    borderTopWidth: 4,
    borderColor: brutalistColors.black,
  },

  iconWrapper: {
    width: "100%",
    justifyContent: "center",
    alignItems: "center",
  },

  retakeOverlayPressed: {
    transform: [{ translateY: 2 }],
  },

  emptySlot: {
    width: "100%",
    aspectRatio: 0.75,
    backgroundColor: brutalistColors.white,
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 4,
    borderColor: brutalistColors.black,
    borderStyle: "dashed",
    minHeight: 200,
  },
  emptyText: {
    marginTop: 12,
    fontSize: 14,
    color: brutalistColors.black,
    fontWeight: "900",
    textTransform: "uppercase",
  },
});

export const attendanceAudioRecorderStyles = audioRecorderStyles;

export const cameraViewStyles = StyleSheet.create({
  container: {
    flex: 1,
  },
  shutterEffect: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "white",
    zIndex: 999,
    opacity: 0,
  },
  overlayContainer: {
    ...StyleSheet.absoluteFillObject,
    justifyContent: "space-between",
    zIndex: 1,
  },
  topControls: {
    position: "absolute",
    top: Platform.OS === "ios" ? 50 : (StatusBar.currentHeight || 30) + 10,
    left: 0,
    right: 0,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 20,
  },
  backButton: {
    backgroundColor: "rgba(0,0,0,0.5)",
    padding: 12,
    borderRadius: 20,
  },
  helpButton: {
    width: 44, // Same width as backButton to maintain layout
  },
  counterOverlay: {
    backgroundColor: "rgba(0,0,0,0.7)",
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 20,
  },
  counterText: {
    color: colors.white,
    fontSize: 16,
    fontWeight: "600",
  },
  quickTipText: {
    color: colors.white,
    fontSize: 14,
    fontWeight: "500",
  },
  faceGuideContainer: {
    position: "absolute",
    top: "40%",
    left: "50%",
    transform: [{ translateX: -100 }, { translateY: -100 }],
  },
  faceGuide: {
    width: 200,
    height: 200,
    justifyContent: "center",
    alignItems: "center",
    position: "relative",
  },
  corner: {
    position: "absolute",
    width: 40,
    height: 40,
    borderColor: "rgba(255,255,255,0.8)",
    borderWidth: 3,
  },
  topLeft: {
    top: 0,
    left: 0,
    borderRightWidth: 0,
    borderBottomWidth: 0,
    borderTopLeftRadius: 20,
  },
  topRight: {
    top: 0,
    right: 0,
    borderLeftWidth: 0,
    borderBottomWidth: 0,
    borderTopRightRadius: 20,
  },
  bottomLeft: {
    bottom: 0,
    left: 0,
    borderRightWidth: 0,
    borderTopWidth: 0,
    borderBottomLeftRadius: 20,
  },
  bottomRight: {
    bottom: 0,
    right: 0,
    borderLeftWidth: 0,
    borderTopWidth: 0,
    borderBottomRightRadius: 20,
  },
  positionIndicator: {
    alignItems: "center",
  },
  positionText: {
    color: "rgba(255,255,255,0.8)",
    fontSize: 14,
    fontWeight: "600",
    marginTop: 8,
  },
  bottomControls: {
    position: "absolute",
    bottom: 20,
    left: 0,
    right: 0,
    alignItems: "center",
  },
  // Preview Styles
  previewContainer: {
    flex: 1,
    backgroundColor: colors.gray[900],
    paddingTop:
      Platform.OS === "ios" ? 60 : (StatusBar.currentHeight || 30) + 20,
  },
  previewHeader: {
    paddingHorizontal: 20,
    paddingBottom: 20,
    alignItems: "center",
  },
  previewTitle: {
    fontSize: 24,
    fontWeight: "600",
    color: colors.white,
    marginBottom: 8,
  },
  previewSubtitle: {
    fontSize: 14,
    color: colors.gray[400],
  },
  photoDisplayContainer: {
    flex: 1,
    marginHorizontal: 20,
    marginBottom: 10,
    borderRadius: 16,
    overflow: "hidden",
    backgroundColor: colors.gray[800],
    position: "relative",
  },
  photoDisplay: {
    width: "100%",
    height: "100%",
  },
  positionBadge: {
    position: "absolute",
    top: 20,
    right: 20,
    backgroundColor: colors.primary[500],
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 12,
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  positionBadgeText: {
    color: colors.white,
    fontSize: 14,
    fontWeight: "600",
  },
  photoInfo: {
    position: "absolute",
    top: 20,
    left: 20,
    backgroundColor: "rgba(0,0,0,0.6)",
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 12,
  },
  photoInfoText: {
    color: colors.white,
    fontSize: 12,
    fontWeight: "500",
  },
  timestampContainer: {
    alignItems: "center",
    paddingVertical: 10,
  },
  timestampText: {
    color: colors.gray[500],
    fontSize: 12,
  },
  previewActions: {
    flexDirection: "row",
    paddingHorizontal: 20,
    paddingBottom: 40,
    gap: 12,
  },
  retakeButton: {
    flex: 1,
    backgroundColor: colors.white,
    paddingVertical: 16,
    borderRadius: 12,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
  },
  retakeButtonText: {
    color: colors.error,
    fontSize: 16,
    fontWeight: "600",
  },
  usePhotoButton: {
    flex: 1.5,
    backgroundColor: colors.success,
    paddingVertical: 16,
    borderRadius: 12,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
  },
  usePhotoButtonText: {
    color: colors.white,
    fontSize: 16,
    fontWeight: "600",
  },
});

export const photoPreviewModalStyles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "rgba(0, 0, 0, 0.9)",
    paddingTop: Platform.OS === "ios" ? 50 : StatusBar.currentHeight || 30,
  },
  content: {
    width: screenWidth - 40,
    maxWidth: 400,
    backgroundColor: colors.white,
    borderRadius: 24,
    padding: 20,
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.3,
    shadowRadius: 20,
    elevation: 20,
  },
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    width: "100%",
    marginBottom: 20,
  },
  photoNumberBadge: {
    backgroundColor: colors.primary[100],
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 12,
  },
  photoNumberText: {
    color: colors.primary[700],
    fontSize: 14,
    fontWeight: "600",
  },
  positionBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    backgroundColor: colors.primary[500],
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 12,
  },
  positionText: {
    color: colors.white,
    fontSize: 14,
    fontWeight: "600",
  },
  photoContainer: {
    width: "100%",
    aspectRatio: 3 / 4,
    borderRadius: 16,
    overflow: "hidden",
    backgroundColor: colors.gray[100],
    marginBottom: 20,
    position: "relative",
  },
  photo: {
    width: "100%",
    height: "100%",
  },
  photoFrame: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    pointerEvents: "none",
  },
  frameCorner: {
    position: "absolute",
    width: 30,
    height: 30,
    borderColor: colors.primary[400],
    borderWidth: 3,
  },
  frameTopLeft: {
    top: 10,
    left: 10,
    borderRightWidth: 0,
    borderBottomWidth: 0,
    borderTopLeftRadius: 8,
  },
  frameTopRight: {
    top: 10,
    right: 10,
    borderLeftWidth: 0,
    borderBottomWidth: 0,
    borderTopRightRadius: 8,
  },
  frameBottomLeft: {
    bottom: 10,
    left: 10,
    borderRightWidth: 0,
    borderTopWidth: 0,
    borderBottomLeftRadius: 8,
  },
  frameBottomRight: {
    bottom: 10,
    right: 10,
    borderLeftWidth: 0,
    borderTopWidth: 0,
    borderBottomRightRadius: 8,
  },
  reviewSection: {
    width: "100%",
    alignItems: "center",
    marginBottom: 24,
  },
  reviewTitle: {
    fontSize: 18,
    fontWeight: "600",
    color: colors.gray[800],
    marginBottom: 4,
  },
  reviewSubtitle: {
    fontSize: 14,
    color: colors.gray[500],
  },
  actions: {
    flexDirection: "row",
    gap: 12,
    width: "100%",
  },
  button: {
    flex: 1,
    borderRadius: 14,
    overflow: "hidden",
  },
  retakeButton: {
    backgroundColor: colors.error + "10",
    borderWidth: 2,
    borderColor: colors.error,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    paddingVertical: 14,
  },
  keepButton: {
    flex: 1.5,
  },
  gradientButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    paddingVertical: 16,
  },
  retakeButtonText: {
    color: colors.error,
    fontSize: 16,
    fontWeight: "600",
  },
  keepButtonText: {
    color: colors.white,
    fontSize: 16,
    fontWeight: "600",
  },
});

export const attendanceCalendarStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.offwhite,
    paddingTop: 16,
    paddingHorizontal: 8,
  },
  loadingContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    paddingVertical: 50,
  },
  loadingText: {
    marginTop: 16,
    fontSize: 18,
    fontWeight: "700",
    color: brutalistColors.text,
  },
  brutalistCardWrapper: {
    marginHorizontal: 16,
    marginBottom: 24,
    backgroundColor: brutalistColors.border,
    transform: [{ translateX: 6 }, { translateY: 6 }],
  },
  brutalistCard: {
    padding: 20,
    borderWidth: 3,
    borderColor: brutalistColors.border,
    backgroundColor: brutalistColors.background,
  },
  headerContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    borderBottomWidth: 3,
    borderColor: brutalistColors.border,
    paddingBottom: 12,
    marginBottom: 16,
  },
  cardTitle: {
    fontSize: 18,
    fontWeight: "900",
    color: brutalistColors.text,
    textTransform: "uppercase",
    textAlign: "center",
  },
  refreshButton: {
    borderWidth: 2,
    borderColor: brutalistColors.border,
    padding: 8,
  },
  simpleStatsGrid: {
    flexDirection: "row",
    justifyContent: "space-around",
    alignItems: "flex-start",
    flexWrap: "wrap",
  },
  simpleStatItem: {
    alignItems: "center",
    paddingHorizontal: 8,
    minWidth: "45%",
    marginBottom: 16,
  },
  simpleStatValue: {
    fontSize: 28,
    fontWeight: "900",
  },
  simpleStatLabel: {
    fontSize: 12,
    fontWeight: "600",
    color: brutalistColors.text,
    marginTop: 4,
    textTransform: "uppercase",
  },
  simpleStatDivider: {
    width: 2,
    height: 50,
    backgroundColor: brutalistColors.border,
  },
  calendar: {
    marginTop: 16,
  },
  selectedDateTitle: {
    fontSize: 16,
    fontWeight: "700",
    color: brutalistColors.text,
    marginBottom: 16,
    borderBottomWidth: 2,
    borderColor: brutalistColors.border,
    paddingBottom: 12,
    flexWrap: "wrap",
  },
  badgeContainer: {
    flexDirection: "row",
    gap: 12,
    marginBottom: 16,
    flexWrap: "wrap",
  },
  attendanceBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderWidth: 2,
    borderColor: brutalistColors.border,
  },
  attendanceBadgeText: {
    fontSize: 14,
    fontWeight: "700",
    textTransform: "uppercase",
  },
  noDataContainer: {
    alignItems: "center",
    paddingVertical: 24,
  },
  noDataText: {
    fontSize: 16,
    fontWeight: "700",
    color: brutalistColors.text,
    marginTop: 12,
    textAlign: "center",
  },
  noDataSubText: {
    fontSize: 14,
    fontWeight: "500",
    color: brutalistColors.text,
    marginTop: 4,
    textAlign: "center",
  },
  attendanceDetailsContainer: {
    gap: 12,
    marginTop: 16,
    paddingTop: 16,
    borderTopWidth: 2,
    borderTopColor: brutalistColors.border,
  },
  attendanceDetailRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  attendanceDetailLabel: {
    fontSize: 14,
    color: brutalistColors.text,
    fontWeight: "700",
    width: 90,
  },
  attendanceDetailValue: {
    fontSize: 14,
    color: brutalistColors.text,
    fontWeight: "500",
    flex: 1,
  },
  legendItems: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 16,
    marginTop: 12,
  },
  legendItem: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  legendDot: {
    width: 16,
    height: 16,
    borderWidth: 2,
    borderColor: brutalistColors.border,
  },
  legendText: {
    fontSize: 14,
    fontWeight: "600",
    color: brutalistColors.text,
  },
});

export const avatarDisplayStyles = StyleSheet.create({
  container: {
    borderColor: "#000000",
    backgroundColor: "#ffffff",
    overflow: "hidden",
    position: "relative",
    shadowColor: "#000",
    shadowOffset: { width: 3, height: 3 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 3,
  },
  webview: {
    flex: 1,
    backgroundColor: "transparent",
  },
  loadingContainer: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.offwhite,
    zIndex: 1,
  },
});

export const avatarPickerStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.offwhite,
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 20,
    paddingTop: 50,
    paddingBottom: 16,
    borderBottomWidth: 4,
    borderColor: "#000",
    backgroundColor: colors.offwhite,
  },
  closeButton: {
    padding: 8,
    borderWidth: 3,
    borderColor: "#000",
    backgroundColor: "#fff",
  },
  headerTitle: {
    fontSize: 20,
    fontWeight: "900",
    color: "#000",
    textTransform: "uppercase",
  },
  placeholder: {
    width: 36,
  },
  content: {
    flex: 1,
    padding: 20,
  },
  section: {
    marginBottom: 30,
  },
  sectionTitle: {
    fontSize: 16,
    fontWeight: "900",
    color: "#000",
    marginBottom: 16,
    textTransform: "uppercase",
    borderBottomWidth: 3,
    borderColor: "#000",
    paddingBottom: 6,
  },
  styleOption: {
    borderWidth: 3,
    borderColor: "#000",
    padding: 12,
    marginRight: 12,
    backgroundColor: "#fff",
    minWidth: 140,
    shadowColor: "#000",
    shadowOffset: { width: 4, height: 4 },
    shadowOpacity: 1,
    shadowRadius: 0,
    elevation: 4,
  },
  selectedStyleOption: {
    backgroundColor: colors.lightGreen,
  },
  styleName: {
    fontSize: 14,
    fontWeight: "700",
    color: "#000",
    textTransform: "uppercase",
  },
  selectedStyleName: {
    color: colors.black,
  },
  styleDescription: {
    fontSize: 12,
    color: "#444",
  },
  avatarGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "space-between",
    gap: 16,
  },
  avatarOption: {
    width: (screenWidth - 60) / 3,
    aspectRatio: 1,
    backgroundColor: "#fff",
    borderWidth: 3,
    borderColor: "#000",
    alignItems: "center",
    justifyContent: "center",
    position: "relative",
    shadowColor: "#000",
    shadowOffset: { width: 4, height: 4 },
    shadowOpacity: 1,
    shadowRadius: 0,
    elevation: 4,
  },
  selectedAvatarOption: {
    backgroundColor: colors.lightYellow,
  },
  selectedBadge: {
    position: "absolute",
    top: 6,
    right: 6,
    width: 20,
    height: 20,
    borderRadius: 10,
    backgroundColor: "red",
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 2,
    borderColor: "#000",
  },
});

export const logoutButtonStyles = StyleSheet.create({
  logoutButton: {
    marginTop: 20,
    marginBottom: 40,
    paddingVertical: 16,
    paddingHorizontal: 20,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 3,
    borderColor: "#000",
    backgroundColor: "#ef4444",
    shadowColor: "#000",
    shadowOffset: { width: 5, height: 5 },
    shadowOpacity: 1,
    shadowRadius: 0,
    elevation: 6,
  },
  logoutButtonText: {
    color: "#000",
    fontSize: 16,
    fontWeight: "900",
    textTransform: "uppercase",
    marginLeft: 10,
  },
  disabled: {
    opacity: 0.5,
  },
});

export const profileContainerStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.offwhite,
  },
  content: {
    padding: 20,
  },
  avatarSection: {
    alignItems: "center",
    marginBottom: 30,
    paddingVertical: 20,
    paddingHorizontal: 10,
    borderBottomWidth: 3,
    borderColor: "#000",
  },
  avatarContainer: {
    borderWidth: 2,
    borderColor: "#000",
    backgroundColor: "#fff",
    shadowColor: "#000",
    shadowOffset: { width: 4, height: 4 },
    shadowOpacity: 1,
    shadowRadius: 2,
    elevation: 2,
    position: "relative",
  },
  avatar: {
    width: 100,
    height: 100,
    backgroundColor: "#000",
    justifyContent: "center",
    alignItems: "center",
  },
  avatarText: {
    fontSize: 32,
    fontWeight: "900",
    color: "#fff",
  },
  editOverlay: {
    position: "absolute",
    bottom: -6,
    right: -6,
    width: 28,
    height: 28,
    backgroundColor: "#000",
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 2,
    borderColor: "#fff",
  },
  usernameText: {
    marginTop: 12,
    fontSize: 22,
    fontWeight: "900",
    color: "#000",
    textTransform: "uppercase",
    textAlign: "center",
    flexWrap: "wrap",
    maxWidth: "90%",
  },
  attendanceCard: {
    borderWidth: 3,
    borderColor: "#000",
    backgroundColor: "#fff",
    padding: 16,
    marginBottom: 20,
    shadowColor: "#000",
    shadowOffset: { width: 5, height: 5 },
    shadowOpacity: 1,
    shadowRadius: 0,
    elevation: 5,
  },
  attendanceCardHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  attendanceCardLeft: {
    flexDirection: "row",
    alignItems: "center",
    flex: 1,
  },
  attendanceCardTextContainer: {
    marginLeft: 12,
    flex: 1,
  },
  attendanceCardTitle: {
    fontSize: 16,
    fontWeight: "900",
    color: "#000",
    marginBottom: 4,
  },
  attendanceCardSubtitle: {
    fontSize: 12,
    color: "#000",
    fontWeight: "600",
  },
  calendarSection: {
    marginTop: -10,
    marginBottom: 20,
  },
  card: {
    borderWidth: 3,
    borderColor: "#000",
    backgroundColor: "#fff",
    padding: 16,
    marginBottom: 20,
    shadowColor: "#000",
    shadowOffset: { width: 5, height: 5 },
    shadowOpacity: 1,
    shadowRadius: 0,
    elevation: 5,
  },
  cardTitle: {
    fontSize: 16,
    fontWeight: "900",
    color: "#000",
    marginBottom: 12,
    textTransform: "uppercase",
  },
  projectsSection: {
    marginTop: 12,
    paddingTop: 12,
    borderTopWidth: 2,
    borderTopColor: "#000",
  },
  projectsLabel: {
    fontSize: 12,
    fontWeight: "900",
    color: "#000",
    marginBottom: 8,
  },
  projectItem: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingVertical: 6,
    paddingHorizontal: 10,
    borderWidth: 2,
    borderColor: "#000",
    backgroundColor: "#fff",
    marginBottom: 6,
  },
  projectText: {
    fontSize: 12,
    color: "#000",
    fontWeight: "700",
  },
  text: {
    marginTop: 10,
    alignItems: "center",
  },
});

export const profileFieldProfileStyles = StyleSheet.create({
  fieldContainer: {
    marginBottom: 20,
  },
  label: {
    fontSize: 14,
    fontWeight: "700",
    color: "black",
    marginBottom: 8,
    textTransform: "uppercase",
  },
  input: {
    backgroundColor: "white",
    borderWidth: 2,
    borderColor: "black",
    padding: 16,
    overflow: "hidden",
  },
  inputContent: {
    flexDirection: "row",
    alignItems: "center",
  },
  icon: {
    marginRight: 12,
  },
  text: {
    fontSize: 16,
    color: "black",
    fontWeight: "600",
    flex: 1,
    flexWrap: "wrap",
  },
});

export const profileHandlerStyles = StyleSheet.create({
  header: {
    paddingTop: Platform.OS === "ios" ? 50 : 30,
    paddingBottom: 20,
    borderBottomWidth: 3,
    borderColor: "black",
    backgroundColor: "#F8F8F8",
  },
  headerContent: {
    alignItems: "center",
    marginTop: 20,
  },
  headerTitle: {
    fontSize: 28,
    fontWeight: "900",
    color: "black",
    textTransform: "uppercase",
  },
  headerSubtitle: {
    fontSize: 14,
    color: "black",
    textAlign: "center",
    marginTop: 4,
  },
});

export const uiButtonStyles = StyleSheet.create({
  primary: {
    backgroundColor: colors.primary[500],
    paddingVertical: 15,
    paddingHorizontal: 30,
    borderRadius: 0,
    alignItems: "center",
  },
  secondary: {
    backgroundColor: colors.secondary[500],
    paddingVertical: 15,
    paddingHorizontal: 30,
    borderRadius: 25,
    alignItems: "center",
  },
  primaryText: {
    color: colors.white,
    fontSize: 18,
    fontWeight: "600",
  },
  secondaryText: {
    color: colors.white,
    fontSize: 18,
    fontWeight: "600",
  },
});

export const termsAndConditionsScreenStyles = StyleSheet.create({
  container: { flex: 1, backgroundColor: colors.offwhite },
  header: {
    paddingTop: Platform.OS === "ios" ? 50 : 30,
    paddingBottom: 20,
    borderBottomWidth: 3,
    borderColor: colors.black,
  },
  headerContent: { alignItems: "center", marginTop: 20 },
  logoBox: {
    width: 80,
    height: 80,
    borderWidth: 3,
    borderColor: colors.black,
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 16,
  },
  headerTitle: {
    fontSize: 28,
    fontWeight: "900",
    color: colors.black,
    textTransform: "uppercase",
  },
  headerSubtitle: {
    fontSize: 14,
    color: colors.black,
    textAlign: "center",
    marginTop: 4,
  },
  contentContainer: { flex: 1 },
  scrollView: { flex: 1, marginBottom: 100 },
  scrollContent: { padding: 16, paddingBottom: 40 },
  section: {
    borderWidth: 3,
    borderColor: colors.black,
    backgroundColor: colors.white,
    padding: 16,
    marginBottom: 20,
  },
  sectionHeader: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 12,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: "900",
    color: colors.black,
    marginLeft: 12,
    textTransform: "uppercase",
  },
  sectionText: {
    fontSize: 14,
    color: colors.black,
    lineHeight: 20,
    marginBottom: 12,
  },
  bulletPoint: {
    flexDirection: "row",
    alignItems: "flex-start",
    marginBottom: 8,
  },
  bulletMarker: {
    fontSize: 16,
    fontWeight: "900",
    color: colors.black,
    marginRight: 8,
  },
  bulletText: { flex: 1, fontSize: 14, color: colors.black, lineHeight: 20 },
  boldText: { fontWeight: "900", color: colors.black },
  dataTypeTitle: {
    fontSize: 14,
    fontWeight: "900",
    color: colors.black,
    marginTop: 12,
  },
  dataDescription: {
    fontSize: 13,
    color: colors.black,
    marginBottom: 8,
    marginLeft: 8,
  },
  scrollIndicator: {
    alignItems: "center",
    marginTop: 20,
    paddingVertical: 12,
    borderTopWidth: 2,
    borderColor: colors.black,
  },
  scrollIndicatorText: { fontSize: 14, color: colors.black, fontWeight: "900" },
  buttonContainer: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    padding: 20,
    paddingBottom: Platform.OS === "ios" ? 40 : 20,
    borderTopWidth: 3,
    borderColor: colors.black,
    backgroundColor: colors.white,
  },
  acceptButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 12,
    borderWidth: 3,
    borderColor: colors.black,
    backgroundColor: colors.lightGreen,
    paddingVertical: 16,
    paddingHorizontal: 24,
  },
  buttonDisabled: {
    backgroundColor: colors.gray[400],
    borderColor: colors.black,
  },
  acceptButtonText: {
    color: colors.black,
    fontSize: 16,
    fontWeight: "900",
    textTransform: "uppercase",
  },
  buttonHelpText: {
    textAlign: "center",
    fontSize: 12,
    color: colors.black,
    marginTop: 8,
  },
});
